### ISSUE TITLE
Add to psget

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/psbuild#22]
We should add psbuild to psget so that users can easily acquire psbuild.

**Comment by mitulsuthar** [comment]
Submitted a pull request to psget project so it will be supported - https://github.com/psget/psget/pull/206 I will update once it is live.

**Comment by mitulsuthar** [comment]
@sayedihashimi For the author field I have added your name and link to your site in the Directory.xml file for PsGet. I hope you don't mind.

**Comment by sayedihashimi** [comment]
@mitulsuthar thanks a lot. I'm not sure how I missed this. This is awesome. I will try it this weekend.
