### ISSUE TITLE
Support special Platform parameter

### ISSUE THREAD

**Issue by Arithmomaniac** [ligershark/psbuild#50]
`Configuration` can be set with a direct command-line parameter rather than through `properties`, presumably because it is in all sln/csproj files and usually needs to be specified for msbuild.

By the same logic, there should be such a `Platform` variable as well.

**Comment by sayedihashimi** [comment]
@Arithmomaniac I agree lets do it. You want to send a PR

**Comment by Arithmomaniac** [comment]
I got shifted off the work project where this was relevant for - if I'm put back on, I'll see what I can do.

**Comment by sayedihashimi** [comment]
Added in commit 3fc7057b7f9709da1ac78f582f954b455e2055af in ```dev``` branch. Please re-open if you have any issues.
