### ISSUE TITLE
Warning about msbuild location is displayed when -msbuildPath is used

### ISSUE THREAD

**Issue by Arithmomaniac** [ligershark/psbuild#51]
If I specify 
`Invoke-MSBuild $slnFile -msbuildPath $msbuildPath -properties $msbuildProperties -Verbose`

I should not see the following warning in my console, especially not in a different color:

    Using msbuild.exe from [C:\Program Files (x86)\MSBuild\12.0\bin\amd64\msbuild.exe]. Use Set-MSBuild to change this.

**Comment by sayedihashimi** [comment]
Thanks for the issue.

I think having "Using msbuild.exe [path]" is still valuable for the log files after the fact. I do agree that when passing the path you should not see Set-MSBuild.

That being said is the highlighting the biggest concern? If so how about we just don't highlight anything?

**Comment by Arithmomaniac** [comment]
That's reasonable

**Comment by sayedihashimi** [comment]
@Arithmomaniac I have made the change in the dev branch. Let me know if we need any further changes, closing now.

**Comment by Arithmomaniac** [comment]
What about not showing "use set-msbuild" when passing the path?

**Comment by sayedihashimi** [comment]
We discussed this above

>That being said is the highlighting the biggest concern? If so how about we just don't highlight anything?

And

>That's reasonable

So I thought the agreement was that removing the highlighting was sufficient? In either case, if you want to conditionally not display the set-msbuild message send a PR and I'll review it. Personally I don't mind it.

**Comment by Arithmomaniac** [comment]
Hi,
I meant that not highlighting as opposed to removing entirely. The "Use Set-MSBuild" message was still bugging me.
If/when I'm reassigned to the project I used this on, I'll fix this. Just leave it open and help-wanted.

**Comment by sayedihashimi** [comment]
@Arithmomaniac OK I was making some other changes and updated this. I think the behavior you are looking for is now in place.
