### ISSUE TITLE
Should be able to turn on/off specific loggers

### ISSUE THREAD

**Issue by Arithmomaniac** [ligershark/psbuild#52]
Having all three loggers always write to disk can slow a build considerably.

**Comment by sayedihashimi** [comment]
Do you want to be able to control globally or on an individual build?

**Comment by Arithmomaniac** [comment]
global is fine (though I think as a general rule, any global setting should be possible to override explicitly)

**Comment by sayedihashimi** [comment]
@Arithmomaniac OK I made the changes. I have added a new global option which is feed into a parameter to ```Invoke-MSBuild```. Take a look at the [diff](https://github.com/ligershark/psbuild/commit/1e71eab43413b7fc36e0bdf6ffa0cae400b8edc8) for usage info. Can you take a look and re-open if this doesn't work for you?
