### ISSUE TITLE
"you can use Open-PSBuildLog to open the log file" should not show when -nologfiles is used

### ISSUE THREAD

**Issue by Arithmomaniac** [ligershark/psbuild#53]
Suppose the following:

     Invoke-MSBuild $slnFile -properties $msbuildProperties -Verbose -nologfiles

After the build, I see

      >>>> Build completed you can use Open-PSBuildLog to open the log file

It should just say

      >>>> Build completed

**Comment by sayedihashimi** [comment]
+1 I've marked it as approved and help wanted.

**Comment by sayedihashimi** [comment]
Updated it to include this, closing. Let me know if you have any feedback. Thanks.
