### ISSUE TITLE
Provide custom directory for log files

### ISSUE THREAD

**Issue by DmitryLobanov** [ligershark/psbuild#69]
Currently PSBuild stores log files in default directory. It would be nice to specify custom directory for logs.

Usecase: we are using multiple build agents on the same server, so technically it is possible that we have the same .proj file being built on >=2 build agents at the same time. In this case there can be conflicts with log files.

**Comment by sayedihashimi** [comment]
Thanks for the report. You can set it by calling Set-PSBuildLogDirectory https://github.com/ligershark/psbuild/blob/master/src/psbuild.psm1#L938. Please try it and let me know if you have any issues.

**Comment by DmitryLobanov** [comment]
Oh, I think this will work just fine. Thanks!
My apologies for not looking into 'Get-Command psbuild' :)

**Comment by sayedihashimi** [comment]
FYI Get-Command -module psbuild will return the full set of commands. Some commands don't have "psbuild" in the name.

**Comment by DmitryLobanov** [comment]
Oh, yeah, thanks, of course it is `Get-Command -module PSBuild`.
