### ISSUE TITLE
GetPSBuild.ps1 fails if run under LocalSystem account

### ISSUE THREAD

**Issue by DmitryLobanov** [ligershark/psbuild#72]
Hello, if we run GetPSBuild.ps1 onto a build agent running under the LocalSystem account (not good :) ), then it fails because it fails to find PS Module directory. The `GetPsModulesPath` function fails.

 > GetPsModulesPath : Cannot bind argument to parameter 'Path' because it is an empty string.

**Comment by sayedihashimi** [comment]
@DmitryLobanov thanks for the report. I haven't tried this yet.

I've made [some changes](https://github.com/ligershark/psbuild/commit/4b888e9dff56c60a0801aecfa18cf805681c5c2f) that I think should fix the issue in the dev branch that should fix this.

Could you update your script to execute the following command and let me know if it works?

```
(new-object Net.WebClient).DownloadString("https://raw.githubusercontent.com/ligershark/psbuild/dev/src/GetPSBuild.ps1") | iex
```

Once that I know it works I'll merge it to master.

Thanks,
Sayed Ibrahim Hashimi

**Comment by DmitryLobanov** [comment]
Thanks for quick reply! 
Do you think it's failing because $env:PSModulePath is empty? I suppose it's the `[Environment]::GetFolderPath('MyDocuments')` returning `string.Empty` or `$null`, because MyDocuments special folde isn't defined for system accounts. Which, in turn, results in `Join-Path` exception with text `GetPsModulesPath : Cannot bind argument to parameter 'Path' because it is an empty string.`
Does it sound reasonable?

**Comment by sayedihashimi** [comment]
Ok so its still failing? I've got that portion in a try/catch so was hoping that would do the trick.

**Comment by DmitryLobanov** [comment]
I haven't tried yet, just wanted to ensure that we are fixing the real cause of problem. I've just pushed our script pointing at your changes (in dev branch), so I'll get back soon with results.

**Comment by DmitryLobanov** [comment]
No, it didn't help. But this time the error is more serious:

> 08-Jun-2015 16:05:33	The command ["C:\Windows\system32\config\systemprofile\AppData\Local\LigerShark
> 08-Jun-2015 16:05:33	\tools\nuget.exe" install psbuild -Version 1.1.3-beta -Prerelease] exited with
> 08-Jun-2015 16:05:33	code [-2146232576]
> 08-Jun-2015 16:05:33	At line:134 char:17
> 08-Jun-2015 16:05:33	+                 throw $msg
> 08-Jun-2015 16:05:33	+                 ~~~~~~~~~~
> 08-Jun-2015 16:05:33	    + CategoryInfo          : OperationStopped: (The command ["C...e [-2146232
> 08-Jun-2015 16:05:33	   576]:String) [], RuntimeException
> 08-Jun-2015 16:05:33	    + FullyQualifiedErrorId : The command ["C:\Windows\system32\config\systemp
> 08-Jun-2015 16:05:33	   rofile\AppData\Local\LigerShark\tools\nuget.exe" install psbuild -Version   
> 08-Jun-2015 16:05:33	  1.1.3-beta -Prerelease] exited with code [-2146232576]

**Comment by sayedihashimi** [comment]
@DmitryLobanov OK this error is different. The install script uses nuget.exe to download a NuGet package which contains the PowerShell module and then loads the module from there. It looks like it's failing on that step.
I'm guessing in your environment the ```nuget.config``` file has some private feeds listed and those feeds don't have psbuild. So, I just made an [update to the script ](c297a09c4ce61ef3705ac36a29641878986922bd) to specify nuget.org as the source.

Can you try again and let me know if that fixes it?

**Comment by DmitryLobanov** [comment]
Doesn't work also. Btw, we don't have private feed listed in nuget.config. Here's the error log:

> The command ["C:\Windows\system32\config\systemprofile\AppData\Local\LigerShark\tools\nuget.exe" install psbuild -Version 1.1.3-beta -Prerelease -source  https://www.nuget.org/api/v2/] exited with code [-2146232576]
> At line:135 char:17
> +                 throw $msg
> +                 ~~~~~~~~~~
> + CategoryInfo          : OperationStopped: (The command ["C...e [-2146232576]:String) [], RuntimeException 
> + FullyQualifiedErrorId : The command ["C:\Windows\system32\config\systemprofile\AppData\Local\LigerShark\tools\nuget.exe" install psbuild -Version 1.1.3-beta -Prerelease -source https://www.nuget.org/api/v2/] exited with code [-2146232576]

**Comment by sayedihashimi** [comment]
@DmitryLobanov OK I think I have fixed it in 69cace60882c184d6c45d801af73a831df1e2e81. I was able to repro it locally. For some reason when running under local system it doesn't like running nuget.exe from %localappdata%. I changed the folder to %temp% and it was fine. Can you try again?

**Comment by DmitryLobanov** [comment]
Hello, not we have this error:

17-Jun-2015 15:46:42	GetPsBuildPsm1 : Cannot bind argument to parameter 'Path' because it is null.
17-Jun-2015 15:46:42	At line:30 char:40
17-Jun-2015 15:46:42	+     [System.IO.FileInfo]$psbPsm1File = GetPsBuildPsm1
17-Jun-2015 15:46:42	+                                        ~~~~~~~~~~~~~~
17-Jun-2015 15:46:42	    + CategoryInfo          : InvalidData: (:) [GetPsBuildPsm1], ParameterBind
17-Jun-2015 15:46:42	   ingValidationException
17-Jun-2015 15:46:42	    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,G
17-Jun-2015 15:46:42	   etPsBuildPsm1

**Comment by DmitryLobanov** [comment]
@sayedihashimi I've fixed 2 issues in pull request (https://github.com/ligershark/psbuild/pull/73). Could you please review it and accept/reject/etc. I've tested it in our infrastructure and it works.

**Comment by sayedihashimi** [comment]
Closing since I think this issue is now resolved, if not please let me know.
