### ISSUE TITLE
Invoke-MSBuild not splatting $ignoreExitCode switch

### ISSUE THREAD

**Issue by mscappini** [ligershark/psbuild#74]
When `Invoke-MSBuild` calls `Invoke-CommandString`, it does not splat the `$ignoreExitCode` switch to the `$ignoreErrors` parameter of `Invoke-CommandString`. Switching this on will not stop `Invoke-CommandString` from throwing `$msg` if there are build errors.

**Comment by sayedihashimi** [comment]
@mscappini thanks for the report, I've fixed it in https://github.com/ligershark/psbuild/commit/3f0b69bc83ac3890b95625b766852af8e313cb70 and released a new version to nuget. If you'd like to try it before I merge to master you can use ```(new-object Net.WebClient).DownloadString("https://raw.githubusercontent.com/ligershark/psbuild/release/src/GetPSBuild.ps1") | iex```

**Comment by mscappini** [comment]
Yep, looks good! Now I can stop using my modified copy. Thanks!

By the way, excellent module! I love it! :+1:
