### ISSUE TITLE
Upload to nuget fails due to old CLI tool

### ISSUE THREAD

**Issue by geonewlitho** [ligershark/psbuild#90]
Hi @sayedihashimi 

It seems that the [last release commit](https://ci.appveyor.com/project/sayedihashimi/psbuild/build/1.0.300) didn't push the package to nuget successfully, even if the build outcome was successful.

The error was: 

> nuget.exe : Failed to process request. 'A client version '4.1.0' or higher is required to be able to push packages. Please contact support@nuget.org to get more details.'.

I've created PR #91  that'll hopefully fix this issue.

As switf action would be greatly appreciated as this is impacting our build environment.

Thanks

**Comment by sayedihashimi** [comment]
Thanks @geonewlitho I've merged one of your PRs and fixed the publish process.

I have fixed issues with publishing and a new package is available on nuget [1.2.0-beta](https://www.nuget.org/packages/psbuild/1.2.0-beta).

I'm closing this now, but please re-open if you're having any issues.
